### ISSUE TITLE
How to add web support?

### ISSUE THREAD

**Issue by saurabh-vlub** [AgoraIO-Community/Agora-Flutter-Quickstart#120]
I am able to use this project on Android and iOS phones. But unable to run it on web, is there any way to add web support in this project?

**Comment by plutoless** [comment]
i'm working on it for the moment. please trace this ticket instead https://github.com/AgoraIO/Flutter-SDK/issues/63#issuecomment-625779802

**Comment by gicountsNIP** [comment]
@saurabh-vlub are you able to use this project within an existing Flutter project?  The reason I ask is because I can run this standalone and it works, but fails when I incorporate it into an existing project.  I'm trying to isolate what are the changes outside of the AndroidManifest and dart files that is stopping it from working.  Thanks.
