### ISSUE TITLE
How to list down all live videos ??

### ISSUE THREAD

**Issue by khaliqdadmohmand** [AgoraIO-Community/Agora-Flutter-Quickstart#122]
Can someone help me that how to list down all live streaming videos ?

**Comment by plutoless** [comment]
you may need to set up a server and maintain it youself.

**Comment by khaliqdadmohmand** [comment]
Any example plz

**Comment by plutoless** [comment]
@khaliqdadmohmand sorry i don't have a complete example for you, but you can set up a server and maintain a websocket connection with client, so that every host when he connects you can record a room on your server via any storage approach e.g. redis/mongodb etc. And when client requests the list you can go grabbing it from your storage. you can remove the room when the host disconnects.
