### ISSUE TITLE
[BUG] portrait mode

### ISSUE THREAD

**Issue by NarHakobyan** [AgoraIO-Community/Agora-Flutter-Quickstart#22]
![Screenshot_20190722-163936](https://user-images.githubusercontent.com/1781506/61633123-725d3780-ac9f-11e9-96a6-6f15a02f84e4.jpg)
I tested this example in IOS and Android, in portrait mode, IOS worked well, but Android breaks the video

**Comment by plutoless** [comment]
not sure what you mean by breaks the video?

**Comment by NarHakobyan** [comment]
Look at me

**Comment by plutoless** [comment]
yes i can now properly see the picture. It seems the orientation is incorrect so that you are seeing a stretched video image. Could you pls try using setVideoEncoderConfiguration to fix the orientation?

**Comment by NarHakobyan** [comment]
but It's working on IOS, It's set to Adaptative

**Comment by plutoless** [comment]
could you pls tell me the actual orientation of your two devices?

**Comment by NarHakobyan** [comment]
I tried to test mobile devices orientations with desktop, so I started Angular starter and connected with ios, after rotating device it's automatically changed orientation, so in desktop, I saw myself in portrait mode, then I tried to run and rotate to the portrate mode It's rotated my video in reverse. Also in desktop, it's not changed anything.

How to reproduce.

1. clone and run angular starter https://github.com/AgoraIO-Community/Angular-Agora-RTC
2. clone and run flutter starter https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart
3. connect to `1000` channel
4. Try rotate android device

**Comment by NarHakobyan** [comment]
Hi @plutoless any news related to this issue?

**Comment by plutoless** [comment]
am working on this. will try to get back to you next week

**Comment by NarHakobyan** [comment]
Hi, any news about this issue?

**Comment by plutoless** [comment]
am working on this. sry is kinda of busy last week

**Comment by NarHakobyan** [comment]
Hi @plutoless, any news about this issue, we need to know is it will be fixed or not, so we can start building our 2 big apss

**Comment by plutoless** [comment]
@NarHakobyan  i double checked the issue on pure native app and it's working properly. My guess is flutter engine is not dealing with the rotation properly in this circumstances. I also found this thread which might be relevant, could you pls give this a shot?

**Comment by NarHakobyan** [comment]
@plutoless I tested with native_device_orientation, it's rotated my screen, but in a remote device, it's shown in the wrong angle

**Comment by plutoless** [comment]
any screenshots?

**Comment by NarHakobyan** [comment]
currently, I don't have a device with me to test, but it rotates local camera view , but in a remote device it shows in the wrong angle

**Comment by plutoless** [comment]
umm i double checked native_device_orientation it seems it's used to help you distinguish landscape left and landscape right, so it might be less relevant in this case.
I believe this issue is caused by a bug for how flutter renders PlatformView on android when rotated - because our native demos all work fine in same circumstances. Since flutter has its own rendering mechanism, it may fail to draw the PlatformView onto its own rendering layer with proper angle.
It seems there's nothing too much we can do until 1. wait for flutter to fix this 2. to switch current SDK implementation from PlatformView to Texture Widget. Approach 2 sounds promising while it requires certain amount of work.

**Comment by NarHakobyan** [comment]
Yeah, It would be nice if it will be fixed, so we can build our two apps with flutter and agora

**Comment by NarHakobyan** [comment]
@plutoless any news about this issue?

**Comment by plutoless** [comment]
unfortunately no. i think we have a colleague named Hermes reaching out you?

**Comment by NarHakobyan** [comment]
Okay I will write in slack

**Comment by wanjm** [comment]
I am waiting for this too;

**Comment by wanjm** [comment]
我觉得问题是SDK不知道当前处于横屏状态, 拿到的还是竖屏的图像, 其他的都没有问题;

**Comment by plutoless** [comment]
@wanjm 我们用native sdk试过 同样的场景下是正常的 目前看起来就是flutter engine在skia渲染时对于子图层的旋转处理有问题

**Comment by wanjm** [comment]
如果是skia渲染有问题, 那么接收端 看到的图像应该是正确的. 实际不是这样, 所以采集到的视频本身就是有问题, 而不是skia渲染的问题;

**Comment by plutoless** [comment]
@wanjm 如果采集和渲染任何一方面有问题，我们的native sdk应该也可以复现这个问题，但事实是用我们native sdk的quickstart尝试是正常的 https://github.com/AgoraIO/Basic-Video-Call/tree/master/One-to-One-Video 而且从代码里也可以很清晰地看到我们并没有做手动旋转之类的事情，完全交由SDK底层控制渲染，完全一样的逻辑在flutter里就会有问题，所以我才会认为skia本身对旋转的处理有些问题

**Comment by NarHakobyan** [comment]
It would be nice if you talk in English

**Comment by wanjm** [comment]
then i use VideoOutputOrientationMode.FixedLandscape; 
it still doesn't work;
but the doc says:
The video encoder always sends the video in landscape mode. The video encoder rotates the original video before sending it and the rotational information is 0. This mode applies to scenarios involving CDN live streaming.

**Comment by wanjm** [comment]
it seems that orientationMode didn't do rotate work; for two end shows the same thing;
what is the result of recorded video; 

I am still looking for some work around; out app is blocked by this now;

**Comment by plutoless** [comment]
@wanjm 
1. i believe it's fine
2. i believe the rotate actually happens in flutter engine render layer, which is not sth we can easily touch. This is why it's tricky

**Comment by wanjm** [comment]
hello all: 
let me describe the problem here, in landscape mode;
1. picture in local preview , it is 90degree rotated;
2. video received by peer, it is also 90degrees rotated;
3. both the above is not acceptable, we need to solve this, maybe it is a problem with flutter engine;

so My plan is;
1. ask agora SDK  to rotate the picture to send the picture out, so that the receive can get the correct video picture 
2. we rotate the local picture as preview, if we can directly use the result of 1, it will be better;
3. does the plan accept able , give me your opinion; 

with reference to [(https://docs.agora.io/en/Video/rotation_guide_android?platform=Android)], it seems that agora SDK can help us do rotate;
but question is:
As the first picture of the "Rotate the Video"  tells, if there is no CDN involved, we should use adaptive; it seems that it is not for us;  any way I will go ahead;

I use the follow code to make it rotate;
```
    var config=VideoEncoderConfiguration();
    config.orientationMode=VideoOutputOrientationMode.FixedLandscape;
    AgoraRtcEngine.setVideoEncoderConfiguration(config);
    _addRenderView(client.uid, (viewId) {
      AgoraRtcEngine.setupLocalVideo(viewId, VideoRenderMode.Fit);
      AgoraRtcEngine.startPreview();
    });
``` 

when i use FixedLandscape , it is tailored; others keeps unchanged on preview;
on the receiver side it is the same as the preview one. 
so i can't where is the rotate;

what i need to do more @plutoless;
@NarHakobyan could you please review my plan and result?

**Comment by LichKing-2234** [comment]
fixed

**Comment by harshbhai** [comment]
Issue still there. any update?

**Comment by LichKing-2234** [comment]
@harsuu942 any screenshot?

**Comment by harsuu942** [comment]
![Screenshot_1626091276](https://user-images.githubusercontent.com/17287262/125285653-80973900-e338-11eb-85a4-dc9323699f73.png)

Capture video from the back camera but in player device it shows rotate video.

**Comment by LichKing-2234** [comment]
You have locked your screen.

**Comment by harsuu942** [comment]
No i don't have locked screen.

**Comment by LichKing-2234** [comment]
@harsuu942 Sorry, I mean locked the screen rotation. If you have not locked the screen rotation, your screen should be horizontal.

**Comment by harsuu942** [comment]
Thanks !!! but lets some have locked screen rotation.how can we achieve this?

**Comment by Shahir1730623** [comment]
> setVideoEncoderConfiguration

Can anyone tell me how to use these for flutter app
