### ISSUE TITLE
[Flutter] Add V/S mode in Agora live video streaming 

### ISSUE THREAD

**Issue by DK024-Dev** [AgoraIO-Community/Agora-Flutter-Quickstart#75]
I have to add dual stream mode or VS mode to live video streaming in my app.  And also put the comment interaction in that .

`AgoraRtcEngine.enableDualStreamMode(true);`

**Comment by LichKing-2234** [comment]
any problem?

**Comment by DK024-Dev** [comment]
I put this line to my code but i doesn't get any response. Can you tell me how to implment the dual or vs mode with comment area?

**Comment by LichKing-2234** [comment]
you can refer to [this doc](https://docs.agora.io/en/Interactive%20Broadcast/media_relay_android?platform=Android)

**Comment by DK024-Dev** [comment]
@LichKing-2234  I am adding to flutter project. This one is not more helpful can you provide other way to implement?

**Comment by plutoless** [comment]
dual stream is not used for vs mode. check out the docs, its main purpose is to send out two streams with large/small resolutions so that receiver side you can pick one to receive depending on your network status.
The docs @LichKing-2234 mentioned above is the correct way to implement vs mode, however this api is not yet available in flutter sdk.
An easy way to achieve similar result is to let two hosts leave current channel and join a new joint one. In this case all audience need to do the same.

**Comment by DK024-Dev** [comment]
Okay thank you @plutoless and @LichKing-2234 for suggestion i check this [https://docs.agora.io/en/Interactive%20Broadcast/media_relay_android?platform=Android](url) . 
However any updates on this api in flutter sdk can you update me.

**Comment by plutoless** [comment]
i think @LichKing-2234 is planning an upgrade and he might be able to include this api.
